#!/bin/bash

maindir="$(pwd)"
ver=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" zkspringboot-starter/pom.xml)
ver=${ver//-SNAPSHOT/}
stamp=$(date +%Y%m%d%H)
target=$1
if [ "$target" == "official" ] ; then
	finalVersion=$ver
else
	finalVersion=$ver-FL-$stamp
fi

echo $finalVersion

set -e

bash ./upVer $ver-SNAPSHOT $finalVersion

mvn clean install -pl zkspringboot-starter -am
mvn source:jar javadoc:jar repository:bundle-create --batch-mode -DskipTests -pl zkspringboot-starter -am

cd $maindir
bash ./prepare-upload.sh $finalVersion
